### PR TITLE
Video tag and ui improvements

### PR DESCRIPTION
**Pull request by alihan**
I added a video tag to display the user's video in the modal if exists. If it doesn't, it still shows the user's picture.
I added a new loading component for a better UI. Also replaced content loader in the user modal. I changed the SEO config with a new URL.

### CODE REVIEW

**Comment by okandavut** [comment]
Hi thanks for the contribution. I could not see the video feature on deployed version can you check and merge conflicts ?
https://findsupeer-git-main.okandavut.vercel.app/
@alihan

**Comment by alihan** [comment]
Hi, can you check it now? It seems working on me.

**Comment by okandavut** [comment]
Yes now it's working but i'm not completely sure about play video when open. Maybe we need to give chance to user for decide to play video. What do you think about it? @alihan

**Comment by alihan** [comment]
Yes, probably it would be better for UX. Thanks for the idea 👍 I will change it.

**Comment by okandavut** [comment]
@alihan i checked it seems really great right now. Thanks for your contribution! :)

**Comment by okandavut** [comment]
I forgot the add you as a contributor. Now i added. Code and Design! :)

**Pull request merged**
